### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by kdm9** [cstritt/popgen#1]
Hello,

Thanks for providing these scripts. If you would like them to, please make it clear that others can use this code for their own analyses by adding a license. Personally I suggest the [MPL v2](https://choosealicense.com/licenses/mpl-2.0/), but any free software license will do.

https://docs.github.com/en/enterprise/2.15/user/articles/adding-a-license-to-a-repository

Thanks

**Comment by cstritt** [comment]
Hi,
Thanks, I wasn't aware of this.
